// ══ Evenements Caraïbes 2026-2027 (genere depuis caraibes-events-2026-2027.json) ══
// 54 evenements culturels + nautiques, geocodes par ile (coords approximatives, centre
// d'ile + jitter). Les dates 'estimated'/'tbd' portent confidence != 'confirmed' :
// a afficher avec prudence. Selection editoriale. Descriptions en anglais (ton luxe,
// coherent avec le reste du site) — les noms d'evenements restent dans leur langue
// d'origine (noms propres).

export const CARIBBEAN_EVENTS = [
  {
    "name": "Fête des Cuisinières",
    "place": "Pointe-à-Pitre — Guadeloupe",
    "island": "Guadeloupe",
    "when": "2026-08-08",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "confirmed",
    "coords": [16.35, -61.5],
    "desc": "A tribute to the women who carry on Creole cuisine — a mass at Saint-Pierre-et-Saint-Paul, a procession in ceremonial madras with musical interludes and quadrille, a grand parade, and a banquet to close the day."
  },
  {
    "name": "Spicemas",
    "place": "St. George's — Grenade",
    "island": "Grenade",
    "when": "2026-08-10",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [12.22, -61.6],
    "desc": "Widely regarded as the most authentic J'ouvert Jab Jab in the Caribbean, followed by Monday Night Mas and the Parade of the Bands — stilt-walking Moko Jumbies and hand-painted Vieux Corps masks in full display."
  },
  {
    "name": "Fête de la Banane",
    "place": "Martinique",
    "island": "Martinique",
    "when": "2026-09-01",
    "badge": "Gastronomy",
    "category": "gastronomie",
    "confidence": "tbd",
    "coords": [14.74, -60.94],
    "desc": "A festival celebrating Martinique's banana industry, its growers and its produce."
  },
  {
    "name": "Jounen Kwéyòl / Journée internationale du créole",
    "place": "Multi-îles",
    "island": "Multi-îles",
    "when": "2026-10-28",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "confirmed",
    "coords": [15.5, -61.32],
    "desc": "Madras and Creole dress worn to work and to school, traditional cuisine and community celebrations across the islands. In Guadeloupe the day is known as 'Kréyòl en mouvman'."
  },
  {
    "name": "World Creole Music Festival",
    "place": "Roseau — Dominique",
    "island": "Dominique",
    "when": "2026-10-23",
    "badge": "Music",
    "category": "musique",
    "confidence": "estimated",
    "coords": [15.51, -61.29],
    "desc": "Three nights of bouyon, cadence-lypso, zouk and soukous, staged alongside Dominica's Creole Day celebrations."
  },
  {
    "name": "Toussaint — illumination des cimetières",
    "place": "Guadeloupe, Martinique",
    "island": "Guadeloupe, Martinique",
    "when": "2026-11-01",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "confirmed",
    "coords": [15.5, -61.22],
    "desc": "Families light hundreds of candles at family graves through the night. The cemeteries of Morne-à-l'Eau (Guadeloupe) and Le Carbet (Martinique) offer the most striking displays."
  },
  {
    "name": "Journées de la Tenue Traditionnelle Martiniquaise",
    "place": "Toute l'île, parade à Fort-de-France — Martinique",
    "island": "Martinique",
    "when": "2026-11-19",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "estimated",
    "coords": [14.7, -60.98],
    "desc": "An island-wide call to wear traditional dress at work, in schools and businesses — grand skirts, madras, starched white suits for the men, and headwraps shaped into elaborate turbans — culminating in a lecture-parade and a grand procession through Fort-de-France."
  },
  {
    "name": "Chanté Nwèl / Noël Kakado",
    "place": "Guadeloupe, Martinique",
    "island": "Guadeloupe, Martinique",
    "when": "2026-12-01",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "confirmed",
    "coords": [15.46, -61.26],
    "desc": "Evenings of Creole Christmas carols shared in private homes and on public squares, with roast pork, boudin, savoury pastries, schrubb and coconut punch — an intimate, unstaged local tradition."
  },
  {
    "name": "Sugar Mas (National Carnival)",
    "place": "Basseterre — Saint-Kitts-et-Nevis",
    "island": "Saint-Kitts-et-Nevis",
    "when": "2026-12-12",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [17.4, -62.65],
    "desc": "A Christmas carnival of masquerade troupes and stilt-walking Mocko Jumbies, culminating in the Grand Parade on New Year's Day."
  },
  {
    "name": "Junkanoo — Boxing Day Parade",
    "place": "Nassau, Bay Street — New Providence",
    "island": "New Providence",
    "when": "2026-12-26",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "confirmed",
    "coords": [25.13, -77.32],
    "desc": "The year's most spirited and elaborate parade — goatskin drums, cowbells, brass and crepe-paper costumes, setting off in the small hours before dawn."
  },
  {
    "name": "Junkanoo — New Year's Day Parade",
    "place": "Nassau, Bay Street — New Providence",
    "island": "New Providence",
    "when": "2027-01-01",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "confirmed",
    "coords": [25.09, -77.36],
    "desc": "Junkanoo's second grand parade, with satellite celebrations across the Family Islands in early January, from Georgetown to Exuma."
  },
  {
    "name": "Carnaval de Guadeloupe",
    "place": "Toute l'île, apogée Pointe-à-Pitre et Basse-Terre — Guadeloupe",
    "island": "Guadeloupe",
    "when": "2027-01-03",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "confirmed",
    "coords": [16.31, -61.54],
    "desc": "Six weeks of Sunday parades across every commune, building to the final days of revelry — skin-drum troupes and snare-drum bands alike, from Mas a Po to Mas a Konn and the tar-daubed Mas a Goudron."
  },
  {
    "name": "Carnaval de Martinique",
    "place": "Fort-de-France — Martinique",
    "island": "Martinique",
    "when": "2027-01-06",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "confirmed",
    "coords": [14.66, -61.02],
    "desc": "Vaval, a giant papier-mâché effigy satirising the year's events, is burned on Ash Wednesday amid oil-and-charcoal-covered Red Devils, burlesque brides and bearded women."
  },
  {
    "name": "Fiestas de la Calle San Sebastián (SanSe)",
    "place": "Vieux San Juan — Porto Rico",
    "island": "Porto Rico",
    "when": "2027-01-21",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "confirmed",
    "coords": [18.32, -66.51],
    "desc": "Puerto Rico's largest festival and the unofficial close of the holiday season — giant Cabezudos, bomba y plena, artisans' stalls and multiple stages centred on the Plaza del Quinto Centenario."
  },
  {
    "name": "Mustique Blues Festival",
    "place": "Mustique",
    "island": "Mustique",
    "when": "2027-01-20",
    "badge": "Music",
    "category": "musique",
    "confidence": "estimated",
    "coords": [12.98, -61.11],
    "desc": "Two weeks of blues at Basil's Bar — discreet, intimate, and famously exclusive."
  },
  {
    "name": "Trinidad and Tobago Carnival",
    "place": "Port of Spain — Trinidad",
    "island": "Trinidad",
    "when": "2027-02-08",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [10.79, -61.14],
    "desc": "The world's definitive carnival. J'ouvert breaks before dawn on the Monday, Pretty Mas takes the streets on Tuesday, with Panorama steelpan, Dimanche Gras and Soca Monarch building through the week — allow the full run, February 3rd to 10th."
  },
  {
    "name": "Mas Domnik",
    "place": "Roseau — Dominique",
    "island": "Dominique",
    "when": "2027-02-08",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [15.47, -61.33],
    "desc": "A largely uncommercialised traditional carnival — Sensay costumes in fibre and ribbon, Darkies and Bwa Bwa figures — widely considered the rawest in the English-speaking Caribbean."
  },
  {
    "name": "Kanaval",
    "place": "Port-au-Prince / Jacmel — Hispaniola",
    "island": "Hispaniola",
    "when": "2027-02-07",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [18.84, -70.08],
    "desc": "Floats, rara processions and Jacmel's celebrated papier-mâché masks. Security conditions should always be verified before any recommendation."
  },
  {
    "name": "Carnaval Dominicano",
    "place": "La Vega, Santiago, Santo Domingo — Hispaniola",
    "island": "Hispaniola",
    "when": "2027-02-01",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [18.8, -70.12],
    "desc": "Horned, cow-bladder-wielding Diablos Cojuelos take the streets, with La Vega as the epicentre and a national parade along Santo Domingo's Malecón."
  },
  {
    "name": "Carnaval de Ponce",
    "place": "Ponce — Porto Rico",
    "island": "Porto Rico",
    "when": "2027-02-03",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [18.28, -66.55],
    "desc": "Multi-horned papier-mâché Vejigantes masks, a tradition unbroken since the 18th century, closing with the ceremonial 'Burial of the Sardine' on Tuesday."
  },
  {
    "name": "Aruba Carnival",
    "place": "Oranjestad — Aruba",
    "island": "Aruba",
    "when": "2027-01-01",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [12.62, -69.89],
    "desc": "Six weeks of celebration — Torch Parade, Lighting Parade, Jouvert Morning and the Grand Parade through Oranjestad, closing with the burning of King Momo on Tuesday night."
  },
  {
    "name": "Karnaval Kòrsou",
    "place": "Willemstad — Curaçao",
    "island": "Curaçao",
    "when": "2027-01-02",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [12.27, -68.91],
    "desc": "The Tumba Festival music competition opens the season, building to the Gran Marcha, the Marcha di Despedida and the burning of Rei Momo."
  },
  {
    "name": "Carnaval de Saint-Barthélemy",
    "place": "Gustavia — Saint-Barthélemy",
    "island": "Saint-Barthélemy",
    "when": "2027-02-07",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [18, -62.75],
    "desc": "A small, local celebration — a parade through Gustavia, closing with the burning of Vaval on Shell Beach on Ash Wednesday."
  },
  {
    "name": "Jamaica Carnival",
    "place": "Kingston — Jamaïque",
    "island": "Jamaïque",
    "when": "2027-04-11",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [18.21, -77.22],
    "desc": "A season of fêtes building to Road March through Kingston — soca-driven, contrary to what visitors often expect of a reggae island."
  },
  {
    "name": "St. Thomas Carnival",
    "place": "Charlotte Amalie — Saint-Thomas",
    "island": "Saint-Thomas",
    "when": "2027-04-25",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [18.44, -64.85],
    "desc": "J'ouvert, a Children's Parade and an Adults' Parade, with Mocko Jumbies and quadrille dancers throughout."
  },
  {
    "name": "St. Maarten Carnival",
    "place": "Philipsburg — Saint-Martin (partie néerlandaise)",
    "island": "Saint-Martin (partie néerlandaise)",
    "when": "2027-04-15",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [18.13, -62.97],
    "desc": "Carnival Village comes alive in Philipsburg with J'ouvert Jump-Up, the Grand Carnival Parade and the closing burning of King Momo."
  },
  {
    "name": "Commémoration de l'abolition de l'esclavage",
    "place": "Martinique",
    "island": "Martinique",
    "when": "2027-05-22",
    "badge": "Public holiday",
    "category": "ferie",
    "confidence": "confirmed",
    "coords": [14.62, -61.06],
    "desc": "A local public holiday marked by ceremonies, bèlè drumming and commemorative marches."
  },
  {
    "name": "Commémoration de l'abolition de l'esclavage",
    "place": "Guadeloupe",
    "island": "Guadeloupe",
    "when": "2027-05-27",
    "badge": "Public holiday",
    "category": "ferie",
    "confidence": "confirmed",
    "coords": [16.27, -61.58],
    "desc": "A local public holiday with gwo ka drumming and ceremonies at the Mémorial ACTe and other sites of remembrance."
  },
  {
    "name": "Commémoration de l'abolition de l'esclavage",
    "place": "Saint-Martin",
    "island": "Saint-Martin",
    "when": "2027-05-28",
    "badge": "Public holiday",
    "category": "ferie",
    "confidence": "confirmed",
    "coords": [18.18, -62.97],
    "desc": "A local public holiday commemorating the abolition of slavery."
  },
  {
    "name": "Terre de Blues",
    "place": "Capesterre-de-Marie-Galante — Marie-Galante",
    "island": "Marie-Galante",
    "when": "2027-05-15",
    "badge": "Music",
    "category": "musique",
    "confidence": "estimated",
    "coords": [16.03, -61.19],
    "desc": "Three days of blues, zouk and Creole music. Logistics require early planning — Marie-Galante is reachable only by ferry."
  },
  {
    "name": "Vincy Mas",
    "place": "Kingstown — Saint-Vincent",
    "island": "Saint-Vincent",
    "when": "2027-06-25",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [13.35, -61.12],
    "desc": "J'ouvert, Mardi Gras and Soca Monarch, in an intimate, unhurried format."
  },
  {
    "name": "St. John Festival (Emancipation Celebration)",
    "place": "Cruz Bay — Saint-John",
    "island": "Saint-John",
    "when": "2027-06-27",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "estimated",
    "coords": [18.43, -64.65],
    "desc": "St. John's emancipation celebration, centred on Cruz Bay."
  },
  {
    "name": "Festival de Gwoka de Sainte-Anne",
    "place": "Sainte-Anne — Guadeloupe",
    "island": "Guadeloupe",
    "when": "2027-07-08",
    "badge": "Music",
    "category": "musique",
    "confidence": "estimated",
    "coords": [16.23, -61.62],
    "desc": "Gwo Ka is inscribed on UNESCO's Intangible Cultural Heritage list; six days of concerts, léwòz dance circles, introductory workshops and cross-generational transmission — Guadeloupe's most important cultural gathering after carnival."
  },
  {
    "name": "Saint Lucia Carnival",
    "place": "Castries — Sainte-Lucie",
    "island": "Sainte-Lucie",
    "when": "2027-07-12",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [14.01, -60.9],
    "desc": "J'ouvert, Monday Mas and the Parade of the Bands — a gentler introduction to Caribbean carnival than Trinidad."
  },
  {
    "name": "Tobago Heritage Festival",
    "place": "Tobago",
    "island": "Tobago",
    "when": "2027-07-15",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "estimated",
    "coords": [11.28, -60.66],
    "desc": "Each village presents its own tradition — an Old Time Wedding in Moriah, the Salaka Feast, ole-time dance and storytelling — the closest the English-speaking Caribbean comes to the French Antilles' heritage days."
  },
  {
    "name": "Carnaval de Santiago de Cuba",
    "place": "Santiago de Cuba — Cuba",
    "island": "Cuba",
    "when": "2027-07-21",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [21.62, -77.7],
    "desc": "Eastern congas, comparsas and drumming — Cuba's oldest carnival, with roots in Afro-Haitian tumba francesa."
  },
  {
    "name": "Antigua Carnival",
    "place": "St. John's — Antigua",
    "island": "Antigua",
    "when": "2027-07-27",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "estimated",
    "coords": [17.16, -61.72],
    "desc": "Carnival City comes alive in St. John's — Panorama, J'ouvert, the Parade of Troupes and Last Lap."
  },
  {
    "name": "Crop Over — Grand Kadooment",
    "place": "Bridgetown / Spring Garden Highway — Barbade",
    "island": "Barbade",
    "when": "2027-08-02",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "confirmed",
    "coords": [13.29, -59.46],
    "desc": "A sugar-harvest festival dating to 1687 — Foreday Morning, the Pic-O-De-Crop finals, Cohobblopot and the Grand Kadooment parade down Spring Garden Highway. The most effortless first taste of Caribbean carnival: better organised than Trinidad, with the beach right there."
  },
  {
    "name": "Spicemas",
    "place": "St. George's — Grenade",
    "island": "Grenade",
    "when": "2027-08-09",
    "badge": "Carnival",
    "category": "carnaval",
    "confidence": "confirmed",
    "coords": [12.18, -61.64],
    "desc": "Preliminary competitions begin in May, with the festival proper opening in early August — J'ouvert Jab Jab, Monday Night Mas and Tuesday's Parade of the Bands with Moko Jumbies and Vieux Corps, no rest day between."
  },
  {
    "name": "Fête des Cuisinières",
    "place": "Pointe-à-Pitre — Guadeloupe",
    "island": "Guadeloupe",
    "when": "2027-08-14",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "estimated",
    "coords": [16.19, -61.66],
    "desc": "A tribute to the women who carry on Creole cuisine, with mass, procession and banquet in ceremonial madras."
  },
  {
    "name": "Fête de Saint-Barthélemy",
    "place": "Gustavia — Saint-Barthélemy",
    "island": "Saint-Barthélemy",
    "when": "2027-08-24",
    "badge": "Heritage",
    "category": "patrimoine",
    "confidence": "confirmed",
    "coords": [17.96, -62.79],
    "desc": "The island's patron saint's day — local boat races, the blessing of the sea, and fireworks over Gustavia."
  },
  {
    "name": "Route du Rhum — Destination Guadeloupe",
    "place": "Saint-Malo → Pointe-à-Pitre — Guadeloupe (arrivée)",
    "island": "Guadeloupe (arrivée)",
    "when": "2026-11-01",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [16.35, -61.5],
    "desc": "Departing Saint-Malo on November 1st, 2026, with 118 boats and a race village running from October 20th — a solo transatlantic crossing of 3,542 miles, finishing at Pointe-à-Pitre over a staggered window: roughly a week for the Ultimes, up to three weeks for the Rhum class."
  },
  {
    "name": "St Barth Cata Cup",
    "place": "Baie de Saint-Jean — Saint-Barthélemy",
    "island": "Saint-Barthélemy",
    "when": "2026-11-16",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [17.92, -62.83],
    "desc": "Formula 18 sport catamarans racing November 18th–22nd, with the full event running the week of the 16th–23rd, capped at 60 crews."
  },
  {
    "name": "ARC — Atlantic Rally for Cruisers",
    "place": "Las Palmas → Rodney Bay — Sainte-Lucie (arrivée)",
    "island": "Sainte-Lucie (arrivée)",
    "when": "2026-11-22",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [14.01, -60.9],
    "desc": "Departing Las Palmas on November 22nd for a 2,700-mile crossing, with prize-giving in Saint Lucia on December 19th — over 200 boats, with the Cape Verde-routed ARC+ arriving at Port Louis Marina, Grenada."
  },
  {
    "name": "Grenada Sailing Week",
    "place": "Port Louis Marina — Grenade",
    "island": "Grenade",
    "when": "2027-01-31",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [12.14, -61.68],
    "desc": "A week of racing based at Port Louis Marina, Grenada."
  },
  {
    "name": "Caribbean Multihull Challenge",
    "place": "Sint Maarten",
    "island": "Sint Maarten",
    "when": "2027-02-04",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [18.13, -62.97],
    "desc": "The Caribbean's only regatta dedicated exclusively to multihulls, with a parallel rally for cruising catamarans."
  },
  {
    "name": "RORC Caribbean 600",
    "place": "Fort Charlotte, English Harbour — Antigua",
    "island": "Antigua",
    "when": "2027-02-22",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [17.12, -61.76],
    "desc": "A 600-mile course around 11 islands — Barbuda, Nevis, St Kitts, Saba, St Barth, St Maarten and Guadeloupe — starting February 22nd, with prize-giving on the 26th."
  },
  {
    "name": "St. Maarten Heineken Regatta",
    "place": "Simpson Bay — Sint Maarten",
    "island": "Sint Maarten",
    "when": "2027-03-04",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [18.09, -63.01],
    "desc": "The Caribbean's largest regatta — over 100 boats, 35 nationalities and 20,000 spectators — always the first weekend of March."
  },
  {
    "name": "St Barths Bucket Regatta",
    "place": "Gustavia — Saint-Barthélemy",
    "island": "Saint-Barthélemy",
    "when": "2027-03-18",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [17.88, -62.87],
    "desc": "Invitation-only, for superyachts of 30 metres and above. A new 2027 format runs four races from Thursday to Sunday, the second-to-last full weekend of March."
  },
  {
    "name": "BVI Spring Regatta & Sailing Festival",
    "place": "Nanny Cay — Tortola",
    "island": "Tortola",
    "when": "2027-03-29",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [18.52, -64.54],
    "desc": "The Scrub Island Invitational on March 30th, the Nanny Cay Cup Round Tortola on the 31st, and the main regatta April 2nd–4th, across nine classes and two fleets."
  },
  {
    "name": "St. Thomas International Regatta",
    "place": "Saint-Thomas",
    "island": "Saint-Thomas",
    "when": "2027-04-08",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [18.4, -64.89],
    "desc": "Moved off the Easter weekend for 2027, with a new wing foil class and the Three Sheets Distance Race & Rally — a 100-mile course from St John to St Croix to St Thomas."
  },
  {
    "name": "Antigua Sailing Week",
    "place": "Antigua",
    "island": "Antigua",
    "when": "2027-04-21",
    "badge": "Regatta",
    "category": "regate",
    "confidence": "confirmed",
    "coords": [17.08, -61.8],
    "desc": "A point-to-point format, with each day's racing finishing at a different destination — cruising and rally classes both welcome. Early-bird entry at $12/foot through October 31st, 2026."
  },
  {
    "name": "Traditour — Tour de Guadeloupe de Voile Traditionnelle",
    "place": "Guadeloupe",
    "island": "Guadeloupe",
    "when": "2027-07-02",
    "badge": "Traditional sailing",
    "category": "voile_traditionnelle",
    "confidence": "estimated",
    "coords": [16.15, -61.48],
    "desc": "A circumnavigation of the island by saintoise, Guadeloupe's traditional sailing craft, with the prologue staged from the fishing port of Sainte-Rose — a proving ground for several Tour des Yoles crews."
  },
  {
    "name": "Tour de Martinique des Yoles Rondes",
    "place": "Martinique",
    "island": "Martinique",
    "when": "2027-07-25",
    "badge": "Traditional sailing",
    "category": "voile_traditionnelle",
    "confidence": "estimated",
    "coords": [14.58, -61.1],
    "desc": "The yole ronde — a keel-less traditional craft balanced by 'bois dressés', wooden poles the 14-to-18-strong crew hang from to windward — is inscribed on UNESCO's register of best safeguarding practices for intangible cultural heritage. One finishing commune per stage; a major sporting and cultural event on the island."
  }
];
