// Donnees des 3 categories "The Caribbean by Land" (Monuments / Hiking / Cycling).
// Contenu reel repris de l'ancienne /historic-sites/caribbean-v2 (ExperienceColumns) ;
// reutilise ici par /historic-sites/caribbean (panneaux) et /historic-sites/caribbean/[section].

export const columns = [
  {
    key: 'monuments',
    title: 'Historic Monuments',
    subtitle: 'Jamaica — Ten Sites of Consequence',
    variant: 'monument',
    items: [
      { name: 'Port Royal', meta: '17th c. · Yacht access · UNESCO 2025', desc: 'For four decades, Port Royal was the most important English city in the Western Hemisphere and the dominant commercial hub of the Caribbean — known as "the wickedest city on earth" for its pirates, privateers, and buccaneers. On June 7, 1692, a catastrophic earthquake swallowed two-thirds of the city beneath the harbor, creating the only submerged urban site in the Americas. Inscribed as a UNESCO World Heritage Site in July 2025.', experience: 'Pre-opening exclusive access with the lead archaeologist of the Jamaica National Heritage Trust (JNHT), guided dive on the 17th-century underwater ruins, candlelit dinner within the ramparts of Fort Charles with a historical reenactment performed by costumed actors.' },
      { name: 'Fort Charles', meta: '1655–1660 · Yacht access', desc: "Fort Charles is the best-preserved colonial military building in Jamaica and one of the oldest in the Caribbean. Built in the shape of a ship, its brick walls — up to six feet thick — once mounted 104 cannons and housed a garrison of 500 men. The young Horatio Nelson commanded the fort's defenses in 1779. The interior Maritime Museum displays 17th-century artifacts recovered from the seabed.", experience: "Exclusive torchlit evening visit with full battlements illuminated, a historian-narrated reenactment of the 1692 earthquake, and a gourmet dinner served on Nelson's quarterdeck overlooking Kingston Harbour." },
      { name: 'Spanish Town', meta: '1534–1872 · Inland transfer', desc: "Spanish Town contains one of the finest Georgian squares in the world — Emancipation Square — enclosed by 18th-century civic buildings: the Former King's House (1762), the Georgian Courthouse, and the Cathedral of St. Jago de la Vega (founded 1525). Beneath the square, Spanish tunnels run from the colonial era. Jamaica's capital for over 300 years.", experience: "Pre-opening private access to the Spanish underground tunnels with a JNHT archaeologist, exclusive after-hours tour of the Archaeological Museum, gala dinner in the courtyard of the Former King's House with a live traditional Jamaican music concert." },
      { name: 'Rose Hall Great House', meta: '1770s · Yacht access', desc: 'Rose Hall is Jamaica\'s most celebrated colonial great house, set on a hill above the Caribbean Sea amid a working sugar plantation. Built in the Georgian style in the 1770s, it is forever linked to the legend of Annie Palmer, the "White Witch." Fully restored with period furnishings, 15 kilometers east of Montego Bay.', experience: 'Exclusive pre-dawn opening with access to the private apartments normally sealed to the public, guided tour by a Georgian-era specialist historian in period costume, candlelit dinner on the grand terrace overlooking the sea.' },
      { name: 'Greenwood Great House', meta: '1780–1800 · Yacht access', desc: 'Greenwood is considered the best-preserved great house in Jamaica, having survived the 1831 slave uprisings entirely intact. The two-story stone and timber house retains its original Georgian furniture, a library of 2,000 antique volumes, and rare 18th-century instruments. The 360-degree panorama over the north coast is breathtaking.', experience: 'Private evening visit with the current owners, access to rooms not open to the public, a recital of period music performed on the original instruments, cocktails on the veranda at sunset.' },
      { name: 'Falmouth', meta: '1769–1840s · Yacht access', desc: "Falmouth preserves the most complete and coherent Georgian townscape in the entire Caribbean: a grid of streets, 18th-century brick and timber buildings, the Albert George Market (1798), the Courthouse (1815), and Water Square — home to an 1798 reservoir predating New York's. The town embodies the full arc of Jamaican sugar wealth.", experience: "Private evening architectural tour with the World Monuments Fund's Georgian heritage specialist, candlelit dinner in one of the restored private historic houses, exclusive access to the William Knibb Museum." },
      { name: 'Seville Heritage Park', meta: 'Since 650 AD · Yacht access', desc: "Considered the birthplace of modern Jamaica: across 300 acres of St. Ann coastline, four civilizations overlap — the Taino village of Maima where Columbus landed in 1494, the first European city in Jamaica (1509), the first sugar mill in the Americas, and the British sugar plantation era. On the UNESCO tentative list since 2009.", experience: 'Private archaeological tour with the JNHT operations director and a Taino specialist archaeologist, exclusive access to active excavation zones, sunset horseback ride across the estate with a gourmet picnic.' },
      { name: 'Devon House', meta: '1881 · Kingston', desc: "Kingston's architectural jewel and the defining monument of Victorian Jamaica. This Caribbean-Georgian manor, set on 11 landscaped acres, was built by George Stiebel, the island's first man of color to achieve millionaire status. The interior preserves an exceptional collection of 19th-century antiques and a grand ballroom.", experience: 'Exclusive gala dinner in the grand ballroom, closed to the public for the occasion, with Victorian-era decor, a menu created by a celebrated Jamaican chef, and a chamber music recital on the original fortepiano.' },
      { name: 'Good Hope Plantation', meta: '1755 · Yacht access', desc: "One of the most spectacular and best-preserved plantation estates in Jamaica, set in the hills of Trelawny on the edge of the Cockpit Country at 1,600 feet. The 1755 Georgian great house, surrounded by 2,000 acres of tropical landscape, retains its original furniture and stables, with extraordinary mountain views.", experience: 'Arrival on horseback across the plantation grounds, private guided tour with a Trelawny historian, a "planter style" gourmet luncheon with produce from the estate, private swimming in the Martha Brae River.' },
      { name: 'Port Antonio', meta: 'Superyacht marina', desc: "Port Antonio is considered one of the most beautiful natural harbors in the Caribbean. The Errol Flynn Marina is the only facility in the Caribbean capable of accommodating the world's largest yacht. The Titchfield Peninsula Historic District preserves some of the finest Victorian and colonial architecture in Jamaica.", experience: "Personalized VIP welcome at the marina, private architectural tour of the Titchfield Peninsula Historic District, gourmet lunch at Norma's at the Marina, private tender excursion to the Blue Lagoon." },
    ],
  },
  {
    key: 'hiking',
    title: 'Hiking',
    subtitle: '20 exceptional hikes · VIP access from the yacht',
    variant: 'hike',
    items: [
      { name: 'La Soufrière', location: 'Guadeloupe', level: 'Difficult', distance: '12 km', elevation: '+1,467 m', duration: '6–8 h', yacht: true, vip: 'Private volcanologist guide (BRGM). Helicopter transfer from yacht to Saint-Claude, gourmet picnic at altitude with champagne, return flight at sunset.', access: 'Basse-Terre or Pigeon Island. Helicopter 15 min.' },
      { name: 'Blue Mountains', location: 'Jamaica', level: 'Difficult', distance: '16 km', elevation: '+2,256 m', duration: '7–9 h', yacht: true, vip: 'Luxury high-altitude bivouac (Frette bedding), Blue Mountain Coffee breakfast at summit, helicopter return with coastal flyover.', access: 'Kingston Harbour or Port Antonio. Private 4x4 (1h30).' },
      { name: 'Boiling Lake', location: 'Dominica', level: 'Very difficult', distance: '13 km', elevation: '+600 m', duration: '6–8 h', yacht: true, vip: 'Certified forest guide, VIP porters, private thermal bath en route, Creole lunch in the forest, on-board massage after return.', access: 'Portsmouth or Roseau. Private 4x4 30 min to Titou Gorge.' },
      { name: 'Petit Piton Summit', location: 'St Lucia', level: 'Difficult', distance: '8 km', elevation: '+743 m', duration: '4–6 h', yacht: true, vip: 'Sunrise ascent, professional photographer, gourmet breakfast at the summit, optional rappel descent, volcanic spa at Sulphur Springs.', access: 'Direct anchorage in Soufrière Bay. Tender 5 min.' },
      { name: 'El Yunque', location: 'Puerto Rico', level: 'Moderate', distance: '8 km', elevation: '+350 m', duration: '3–5 h', yacht: false, vip: 'Pre-dawn private access, US Forest Service naturalist, private swim under La Mina Falls, helicopter return along east coast.', access: 'Fajardo marina. Private SUV 35 min to park.' },
      { name: 'Mount Scenery', location: 'Saba', level: 'Moderate', distance: '5 km', elevation: '+877 m', duration: '3–4 h', yacht: false, vip: 'Charter flight Sint Maarten → Saba (12 min), private botanist guide, cloud forest picnic, Saba Marine Park dive on return.', access: 'Charter flight from Sint Maarten (12 min).' },
      { name: 'Montagne Pelée', location: 'Martinique', level: 'Difficult', distance: '14 km', elevation: '+1,397 m', duration: '6–8 h', yacht: true, vip: 'Expert volcanologist, helicopter to trailhead, inner crater access (off-trail), gastronomic lunch in Saint-Pierre ruins.', access: 'Saint-Pierre anchorage. Private 4x4 30 min.' },
      { name: 'The Quill', location: 'Sint Eustatius', level: 'Moderate', distance: '6 km', elevation: '+600 m', duration: '3–4 h', yacht: false, vip: 'Private hike + historic museum, Creole lunch in a colonial house, wreck diving in Oranjestad Bay.', access: 'Charter flight from Sint Maarten (15 min).' },
      { name: 'Waitukubuli Trail §7', location: 'Dominica', level: 'Difficult', distance: '12 km', elevation: '+800 m', duration: '5–7 h', yacht: true, vip: '2 days at Jungle Bay Resort eco-lodge, dawn parrot watching, certified Waitukubuli guide, tropical massage at dusk.', access: 'Prince Rupert Bay or Roseau. Private 4x4 45 min.' },
      { name: 'Grand Etang & Seven Sisters Falls', location: 'Grenada', level: 'Moderate', distance: '10 km', elevation: '+450 m', duration: '4–6 h', yacht: true, vip: 'Naturalist guide, fresh cacao tasting, swim in natural pools, lunch at Belmont Estate, rum tasting at River Antoine Distillery.', access: "St George's Harbour or Grand Anse. Private 4x4 30 min." },
      { name: 'Nevis Peak', location: 'Nevis', level: 'Difficult', distance: '10 km', elevation: '+985 m', duration: '5–7 h', yacht: true, isNew: true, vip: "Private mountain guide, champagne at cloud-shrouded summit, plantation lunch at Montpelier Estate, tender pickup from Pinney's Beach.", access: 'Charlestown anchorage. Tender to pier + 4x4 20 min.' },
      { name: 'Soufrière Hills Exclusion Zone', location: 'Montserrat', level: 'Moderate', distance: '6 km', elevation: '+300 m', duration: '3–4 h', yacht: true, isNew: true, vip: 'Volcanologist escort into the exclusion zone, helicopter overflight of the active dome, Plymouth ruins visit, rum punch on return.', access: 'Little Bay anchorage. Helicopter from yacht deck (10 min).' },
      { name: 'Morne Trois Pitons', location: 'Dominica', level: 'Difficult', distance: '14 km', elevation: '+1,342 m', duration: '7–9 h', yacht: true, isNew: true, vip: 'UNESCO World Heritage hike, private guide, boiling springs en route, secluded waterfall swim, helicopter extraction at dusk.', access: 'Roseau anchorage. Private 4x4 40 min to Laudat.' },
      { name: 'Pic Paradis', location: 'St Martin', level: 'Moderate', distance: '8 km', elevation: '+424 m', duration: '3–4 h', yacht: true, isNew: true, vip: 'Dawn ornithologist guide, hummingbird spotting, French-Creole gourmet brunch at a hillside villa, champagne at the viewpoint.', access: 'Marigot or Simpson Bay. Private car 25 min.' },
      { name: 'Mount Obama (Boggy Peak)', location: 'Antigua', level: 'Moderate', distance: '7 km', elevation: '+402 m', duration: '3–4 h', yacht: true, isNew: true, vip: 'Views of 365 beaches, post-hike sailing tour of the south coast, sundowners at English Harbour on a vintage sloop.', access: 'Falmouth or English Harbour. Private vehicle 30 min.' },
      { name: 'Gros Morne (Signal Hill)', location: 'St Vincent', level: 'Difficult', distance: '12 km', elevation: '+1,234 m', duration: '6–8 h', yacht: true, isNew: true, vip: 'Rare St Vincent parrot encounter at dawn, gourmet Vincentian ridge picnic, tender pickup on the leeward coast.', access: 'Kingstown anchorage. Private 4x4 45 min to Vermont Trails.' },
      { name: 'Soufrière Volcano', location: 'St Vincent', level: 'Difficult', distance: '13 km', elevation: '+1,234 m', duration: '6–8 h', yacht: true, isNew: true, vip: 'Specialist volcanologist, pre-dawn departure for crater sunrise, helicopter overflight of caldera lake, spa on the yacht.', access: 'Georgetown anchorage or helicopter from yacht deck.' },
      { name: 'Mount Hillaby Ridge', location: 'Barbados', level: 'Moderate', distance: '9 km', elevation: '+340 m', duration: '3–5 h', yacht: true, isNew: true, vip: 'Heritage guide through the Scotland District, colonial chattel house visit, fine dining at The Cliff restaurant at sunset.', access: 'Bridgetown or Carlisle Bay. Private car 35 min.' },
      { name: 'El Toro Peak', location: 'Puerto Rico (SW)', level: 'Difficult', distance: '14 km', elevation: '+1,075 m', duration: '6–7 h', yacht: false, isNew: true, vip: 'Helicopter to trailhead, USFWS ranger escort to the restricted summit, flyover return along the karst coast.', access: 'San Juan marina. Helicopter to trailhead (25 min).' },
      { name: 'Blue Mountains – Cuna Cuna Pass', location: 'Jamaica (east)', level: 'Difficult', distance: '18 km', elevation: '+1,800 m', duration: '8–10 h', yacht: true, isNew: true, vip: 'Wilderness traverse with a Maroon cultural guide, overnight at private off-grid mountain lodge, coffee ceremony at dawn, helicopter return.', access: 'Port Antonio anchorage. Private 4x4 1h to Rio Grande Valley.' },
    ],
  },
  {
    key: 'cycling',
    title: 'Cycling',
    subtitle: 'Routes & rides',
    placeholder: true,
    items: [
      { name: 'Blue Mountain Descent' },
      { name: 'North Coast Coastal Ride' },
      { name: 'Negril — Seven Mile' },
      { name: 'Cockpit Country Gravel' },
      { name: 'Port Antonio Hills' },
      { name: 'Kingston — St. Thomas Loop' },
    ],
  },
];

export const SECTION_META = {
  monuments: { eyebrow: 'Caribbean · Private Client Guide', title: 'Historic Monuments' },
  hiking: { eyebrow: 'Caribbean · Private Client Guide', title: 'Hiking' },
  cycling: { eyebrow: 'Caribbean · Private Client Guide', title: 'Cycling' },
};
