// Sites historiques des Bahamas (document client « Bahamas_Heritage_Sites_Client_Edition »,
// 2026-10-09) : nom, lieu, description + periode historique, acces yacht, experience VIP.
// Photos : photos Bahamas deja sur le site, en attendant celles du client.

export const BAHAMAS_HERITAGE = {
  key: 'monuments',
  title: 'Heritage Sites',
  subtitle: 'Curated Cultural & Historic Excursions',
  variant: 'monument',
  items: [
    {"name": "Fort Fincastle", "meta": "Nassau · Yacht access", "desc": "Fort Fincastle is a historic fortress perched atop Bennett's Hill in Nassau, built to protect the capital from pirates and foreign invaders. Its distinctive ship-shaped design and cannon-lined ramparts overlook the harbor. The fort now serves as a museum and viewpoint, offering sweeping vistas over downtown Nassau and the turquoise waters beyond. Built in 1793 under Governor Lord Dunmore during British colonial rule. Named after Lord Fincastle, son of the Earl of Dunmore. Part of Nassau's historic fortification system alongside Fort Charlotte and Fort Montagu.", "experience": "A private sunset tour with an appointed Bahamian historian, exclusive access to the illuminated ramparts, and a champagne toast overlooking the harbor; option of a curated heritage dinner in the fort's grounds with live Junkanoo music.", "img": "/media/client/lydie/2026-09-28/bahamas-cards/card-1-color.jpg"},
    {"name": "Queen's Staircase", "meta": "Nassau · Yacht access", "desc": "The Queen's Staircase is a monumental limestone stairway of 66 steps, hand-carved by enslaved Africans in the late 18th century. Flanked by towering rock walls and shaded by mature trees, it connects downtown Nassau to Fort Fincastle. The site stands as a powerful tribute to the resilience and labor of the Bahamian people. Carved between 1793 and 1794 during the governorship of Lord Dunmore. Named in honor of Queen Victoria following the abolition of slavery in the British Empire in 1834. A protected historic landmark and one of the most visited sites in The Bahamas.", "experience": "An exclusive early-morning private walk with a cultural guide, a storytelling session on the history of slavery and emancipation in The Bahamas, and a bespoke Bahamian breakfast served in a shaded garden courtyard.", "img": "/media/client/lydie/2026-09-27/bahamas-hero/poster.jpg"},
    {"name": "Fort Charlotte", "meta": "Nassau · Yacht access", "desc": "Fort Charlotte is the largest and most elaborate of Nassau's three historic forts, featuring massive stone walls, a moat, drawbridge, and underground tunnels. Its strategic hilltop position commands views over the harbor and western approaches to the city. The fort now hosts cultural events and offers guided tours of its military architecture. Constructed in the late 18th century, beginning in 1788 under British colonial administration. Named after Queen Charlotte, wife of King George III. One of the finest examples of Georgian military engineering in The Bahamas.", "experience": "A private twilight tour of the fort's tunnels and ramparts with a military historian, a curated rum and conch fritter tasting in the courtyard, and an optional gala dinner under the stars with live acoustic performances.", "img": "/media/client/lydie/2026-09-27/bahamas-flowers/nassau-color.jpg"},
    {"name": "Elbow Reef Lighthouse", "meta": "Hope Town, Abacos · Yacht access", "desc": "The Elbow Reef Lighthouse is a striking red-and-white striped tower standing sentinel over the treacherous Elbow Reef passage. One of the last manually operated kerosene lighthouses in the world, it remains an iconic symbol of Bahamian maritime heritage. Visitors can climb its 101 steps for panoramic views of Hope Town and the surrounding cays. Built in 1862 by British colonial authorities following a series of devastating shipwrecks. Constructed from local limestone and painted in distinctive candy-cane bands. A protected historic landmark and active aid to navigation.", "experience": "A private sunrise climb with a lighthouse keeper, a champagne breakfast on the gallery deck, and an exclusive photo session capturing the pastel rooftops of Hope Town from above.", "img": "/media/client/lydie/2026-09-28/bahamas-cards/card-4-color.jpg"},
    {"name": "The Hermitage", "meta": "Mount Alvernia, Cat Island · Yacht access", "desc": "The Hermitage is a remarkable stone monastery perched atop Mount Alvernia, the highest point in The Bahamas. Built by hand by Father Jerome, a Franciscan friar, it features a chapel, living quarters, and a bell tower constructed from local limestone. The site offers breathtaking views across Cat Island and the surrounding Atlantic. Constructed between 1939 and 1967 by Father Jerome (John Hawes), an English friar who lived as a hermit on the mountain. A unique example of religious architecture in The Bahamas and a site of spiritual pilgrimage.", "experience": "A private guided hike to the summit with a local historian, a contemplative moment in the chapel with Gregorian chant recordings, and a bespoke picnic lunch with panoramic ocean views.", "img": "/media/client/lydie/2026-09-28/bahamas-cards/card-8-color.jpg"},
    {"name": "Columbus Monument", "meta": "San Salvador · Yacht access", "desc": "The Columbus Monument marks the traditional site of Christopher Columbus's first landing in the New World on October 12, 1492. A tall stone cross stands on a cliff overlooking Long Bay, commemorating this pivotal moment in world history. The site includes interpretive displays and a small museum detailing the island's Lucayan heritage. Erected in the 20th century to commemorate the quincentenary of Columbus's voyage. San Salvador, formerly known as Watling Island, is widely accepted by historians as Columbus's Guanahani. A site of global historical significance.", "experience": "A private sunrise ceremony at the monument with a maritime historian, a curated exhibition on Lucayan culture and the Age of Exploration, and a champagne toast overlooking the bay where Columbus first anchored.", "img": "/media/client/lydie/2026-09-28/bahamas-cta/atlantis.jpg"},
    {"name": "Pompey Monument", "meta": "Rolle Town, Great Exuma · Yacht access", "desc": "The Pompey Monument honors Pompey, an enslaved Bahamian who led a courageous rebellion in 1830. Located in Rolle Town, the monument stands as a testament to the struggle for freedom and dignity in The Bahamas. The site includes interpretive panels and a small memorial garden. Commemorates the 1830 slave uprising led by Pompey on the Rolle plantation. Erected in the 20th century as part of The Bahamas' national heritage preservation efforts. A key landmark in the narrative of Bahamian emancipation.", "experience": "A private guided tour with a cultural historian specializing in Bahamian slavery and emancipation, a storytelling session under the monument's shade, and a curated lunch featuring traditional Exumian cuisine.", "img": "/media/client/lydie/2026-09-28/bahamas-cards/card-3-color.jpg"},
    {"name": "Dunmore Town Historic District", "meta": "Harbour Island · Yacht access", "desc": "Dunmore Town is one of the oldest settlements in The Bahamas, featuring a collection of well-preserved colonial cottages painted in soft pastels. Its narrow streets, historic churches, and waterfront promenade evoke the charm of 18th-century Bahamian life. The town was once the capital of The Bahamas under Governor Lord Dunmore. Established in the 1780s by Loyalist refugees fleeing the American Revolution. Named after John Murray, 4th Earl of Dunmore, who served as Governor of The Bahamas. A designated historic district with strict preservation guidelines.", "experience": "A private walking tour with a heritage architect, exclusive access to a restored Loyalist cottage for afternoon tea, and a sunset cocktail reception on a historic waterfront veranda.", "img": "/media/client/lydie/2026-09-28/bahamas-cards/card-5-color.jpg"},
    {"name": "Lucayan National Park", "meta": "Grand Bahama · Yacht access", "desc": "Lucayan National Park protects one of the world's most extensive underwater cave systems and significant archaeological sites of the indigenous Lucayan people. The park features boardwalk trails through diverse ecosystems, from mangrove forests to pristine beaches. It is a sanctuary of natural and cultural heritage. Established in 1982 to preserve the island's unique karst landscape and Lucayan heritage. Contains evidence of pre-Columbian settlement dating back over 1,000 years. A nationally protected site of exceptional cultural and natural importance.", "experience": "A private guided expedition with an archaeologist and naturalist, subject to park authorization, followed by a bespoke beachside dinner featuring traditional Bahamian flavors under the stars.", "img": "/media/client/lydie/2026-09-28/bahamas-cards/card-2-color.jpg"},
    {"name": "Dolphin House Museum", "meta": "North Bimini · Yacht access", "desc": "The Dolphin House Museum is a whimsical folk-art environment created by local artist Ashley Saunders. Constructed from conch shells, coral, and recycled materials, the structure reflects Bimini's maritime culture and creative spirit. It stands as a unique testament to island ingenuity and artistic expression. Built over several decades beginning in the 1980s by Ashley Saunders, a Bimini native and self-taught artist. A grassroots heritage site celebrated for its eccentric charm and cultural authenticity.", "experience": "A private tour with a local artist or cultural guide, a hands-on shell-craft workshop, and a curated seafood lunch at a waterfront restaurant with views of Bimini's turquoise shallows.", "img": "/media/client/lydie/2026-09-28/bahamas-cards/card-7-color.jpg"},
  ],
};
